apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-ai
  template:
    metadata:
      labels:
        app: devops-ai
    spec:
      containers:
      - name: devops-ai
        image: genai-devops-app:latest
        ports:
        - containerPort: 5000
